version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    container_name: xmr-pay-hub
    ports:
      - "8090:80"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN
    depends_on:
      - app   
